name: Caching And Artifacts
on: [workflow_dispatch]
jobs:
    use-axios:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: npm install
            - name: Use Axios
              uses: actions/github-script@v6
              with:
                script: |
                  const axios = require('axios');
                  const res = await axios('https://github.com/15Dkatz/official_joke_api.git', { headers: { Accepts: 'text/plain' } })
                  console.log(res.data)
