name: checkout 
on: [push]
jobs:
    checkout-and-display:
        runs-on: ubuntu-latest
        steps:
            - name: List files before 
              run: ls -a
            - name: checkout
              run: |
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main
            - name: List Files After
              run: ls -a