name: Docker
on: [workflow_dispatch]
jobs:
    docker-job:
        runs-on: ubuntu-latest
        container: #node:20.3-alpine3.17
           image: node:20.3-alpine3.17
           #credentials:
            #username:
            #password
           env: 
             API_URL: some-url.com
        steps:
            - name: Log node & os VErsions
              run: |
                node -v
                cat /etc/os-release
            - name: Log ENV
              run: echo $API_URL
            - name: Container in a step
              uses: docker://node:18.16-alpine3.17
              with: 
                entrypoint: /usr/local/bin/node  # over ride the entry point parameteers that passed in the docker image define above
                args: -p 2+3
            - name: Log node version
              uses: docker://node:18.16-alpine3.17
              with:
                args: -v
            - name: show file content
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: cat
                args: tetx.txt
            - uses: actions/checkout@v3
            - name: Run a Bash script
              uses: docker://node:18.16-alpine3.17
              with: 
                entrypoint: ./script.sh
                args: "some string" 