name: Environment variables
on: [push]
jobs:
    env-vars-and-context:
        runs-on: ubuntu-latest
       # if: $GITHUB_REF=='ref/heads/main'
        if: github.ref =='refs/heads/main'
        steps:
            - name: Log Env VAR
              run: echo $GITHUB_REF  # this is evaluated by the runner machine
            - name: log context
              run: echo '${{ github.ref }}' # this is evaluated by the GHA Before sending your W.F to the runner machune