name: Expressions and contexts
on: [push,pull_request,issues,workflow_dispatch]
run-name: "Expression & context by @${{ github_actor }},event: ${{ github.event_name }}"
jobs:
    using-expression-and-context:
        runs-on: ubuntu-latest
        steps:
            - name: Expressions
              id: expressions
              run: |
                echo ${{ 1 }}
                echo ${{ 'This is a string' }}
                echo ${{ null }}
                echo ${{ 1>2 }}
                echo ${{ 'string'=='string' }}
                echo ${{ true && false}}
                echo ${{ true ||(false &&true) }}
            - name: dump Context
              run: |
                echo '${{ toJson(github) }}'
                echo '${{ toJson(job) }}'
                echo '${{ toJson(secrets) }}'
                echo '${{ toJson(steps) }}'
                echo '${{ toJson(runner) }}'
