name: First Workflow

on: [push]

jobs:
  run-shell-commands:   # job id
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello GithubActions user"

      - name: multiple line commands
        run: |
          node -v
          npm -v
