name: First Workflow

on: [push]

jobs:
  run-shell-commands:   # job id
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello GithubActions user"

      - name: multiple line commands
        run: |
          node -v
          npm -v
  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: view sw version
        run: sw_vers
  dependant_job:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: echo a string
        run: write-Output "windows string"
      - name: error step
        run: doesnotexits
      
