name: Manual Trigger
on: 
    workflow_dispatch:
        inputs:
            string:
                description: Astring input
                type: string 
                required: true
                default: "Deafult value"
            number:
                description: A integral value
                type: number
                required: true
                default: 4

jobs:
    log-info:
        runs-on: ubuntu-latest
        steps:
            - run: echo $GITHUB_REF