name: Pull Request Coment
on:
    pull_request_target:
        type: [opened]
jobs:
    pr-comment:
        runs-on: ubuntu-latest
        steps:
            - name: Comment On New PRs
              uses: actions/github-script@v6
              script: |
                github.rest.issues.createComment({
                    owner:context.repo.owner,
                    repo:context.repo.repo,
                    issue_number:context.issue.number,
                    body:'Thanks for contributing',
                });