name: Simple Action
on: [push]
jobs:
    simple-action:
        runs-on: ubuntu-latest
        steps:
            - name: simple js action
              id: greet
              uses: actions/hello-world-javascript-action@v1  #username/reponame@branchname/@version actions/hello-world-javascript-action@main/@v1/@commit-id
              with: # to define inputs
                who-to-greet: Sreeja
            - name: log greeting time
              run: echo "${{steps.greet.outputs.time}}"

