name: status check function
on: [push]
jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: step-1
              run: sleep 20
            - name: Runs on Failure
              if: failure()
              run: echo 'Runs only on failure'
            - name: Runs on success
              if: success()
              run: echo 'Runs on success'
            - name: Always
              if: always()
              run: echo 'Always Runs'
    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        if: failure()
        steps:
            - run: echo 'Job 2'