name: status check function
on: [push]
jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: step-1
              run: sleep 20
            - name: step 2
              id: step-2
              run: exit 1
            - name: Runs on step2 Failure
             # if: steps.step-2.conclusion=='failure' # in the background it treats as success so this step does not execute
              if : failure() && steps.step-2.conclusion =='failure'
              run: echo 'step 2 has failed'
            - name: Runs only fails
              if: failure()
              run: echo " failures onl"
            - name: Runs on success
              if: success()
              run: echo 'Runs on success'
            - name: Always
              if: always()
              run: echo 'Always Runs'
            - name: Runs on cancelled
              if: cancelled()
              run: echo "runs on cancelled"
    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        if: failure()
        steps:
            - run: echo 'Job 2,2'