name: Variables and secrets
on: [push]
jobs:
    log-files:
        runs-on: ${{ vars.JOBS_RUNNER }}
        env:
            BOOLEAN_SECRET: ${{ secrets.BOOLEAB_SECRET }}
            ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
            REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
            ORG_LEVEL_VAR: ${{ vars.ORG_LEVEL_VAR }}
        steps:
            - name: RUN only if BOOLEAn secret is true
              if: env.BOOLEAN_SECRET =='true'
              run: echo " I RAN "
            - name: log vars
              run: |
                echo '${{ vars.JOBS_RUNNER }}'
                echo "ORG_LEVEL_VAR: $ORG_LEVEL_VAR"
                echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"
                echo "ENV_LEVEL_VAR: $REPO_LEVEL_VAR"