name: workflow Run
on:
    workflow_run:
        workflows: [Repository Events]
        types: [completed]
        branches:
            - main
jobs:
    echo-string:
        runs-on: ubuntu-latest
        steps:
            - run: echo "I was triggered beacause 'Repositoty Events' was completed"
